name: Build OpenWrt

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf update -y
          dnf install -y findutils gcc gcc-c++ git make ncurses-devel patch \
                         python3 rsync tar unzip wget which zlib-devel \
                         perl-FindBin perl-Thread-Queue perl-IPC-Cmd \
                         perl-core file glibc-static

      - name: Unshallow git repository
        run: git fetch --unshallow
        working-directory: ${{ github.workspace }}

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
        working-directory: ${{ github.workspace }}

      - name: Copy build configuration
        run: cp .config.bpi-rv2 .config
        working-directory: ${{ github.workspace }}

      - name: Cache build directories
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/staging_dir
            ${{ github.workspace }}/build_dir
            ${{ github.workspace }}/dl
          key: ${{ runner.os }}-openwrt-${{ hashFiles(format('{0}/.config', github.workspace)) }}
          restore-keys: |
            ${{ runner.os }}-openwrt-

      - name: Prepare configuration
        run: make defconfig
        working-directory: ${{ github.workspace }}

      - name: Run the build
        run: make -j$(nproc) V=s
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        working-directory: ${{ github.workspace }}

      - name: Package build artifacts
        run: |
          tar -czf openwrt-packages.tar.gz -C bin packages
          tar -czf openwrt-toolchain.tar.gz -C bin toolchain
          tar -czf openwrt-sdk.tar.gz -C bin sdk
        working-directory: ${{ github.workspace }}

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware-bpi-rv2
          path: ${{ github.workspace }}/bin/targets/siflower/sf21/*-sysupgrade.bin

      - name: Upload Packages Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-packages
          path: ${{ github.workspace }}/openwrt-packages.tar.gz

      - name: Upload Toolchain Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-toolchain
          path: ${{ github.workspace }}/openwrt-toolchain.tar.gz

      - name: Upload SDK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-sdk
          path: ${{ github.workspace }}/openwrt-sdk.tar.gz

