name: Build OpenWrt with Packages, SDK, & Toolchain

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf update -y
          dnf install -y findutils gcc gcc-c++ git make ncurses-devel patch \
                         python3 rsync tar unzip wget which zlib-devel

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy build configuration
        run: cp .config.snapshot .config

      - name: Run the build
        run: make -j$(nproc)

      # --- New steps to package the kmods and other packages ---
      - name: Package All Packages
        run: tar -czf openwrt-packages.tar.gz -C bin packages

      - name: Package Toolchain
        run: tar -czf openwrt-toolchain.tar.gz -C bin toolchain

      - name: Package SDK
        run: tar -czf openwrt-sdk.tar.gz -C bin sdk

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware-bpi-rv2
          path: bin/targets/siflower/sf21/*-sysupgrade.bin

      # --- New upload step for the packages ---
      - name: Upload Packages Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-packages
          path: openwrt-packages.tar.gz

      - name: Upload Toolchain Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-toolchain
          path: openwrt-toolchain.tar.gz

      - name: Upload SDK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-sdk
          path: openwrt-sdk.tar.gz
