name: Build OpenWrt with Caching and Dependencies

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          dnf update -y
          dnf install -y findutils gcc gcc-c++ git make ncurses-devel patch \
                         python3 rsync tar unzip wget which zlib-devel \
                         perl-FindBin perl-Thread-Queue perl-IPC-Cmd \
                         perl-core file glibc-static

      - name: Update and install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy build configuration
        run: cp .config.bpi-rv2 .config

      - name: Cache build directories
        uses: actions/cache@v4
        with:
          path: |
            staging_dir
            build_dir
            dl
          key: ${{ runner.os }}-openwrt-${{ hashFiles('.config') }}
          restore-keys: |
            ${{ runner.os }}-openwrt-

      - name: Prepare configuration
        run: make defconfig

      - name: Run the build (Verbose)
        run: FORCE_UNSAFE_CONFIGURE=1 make -j1 V=s

      - name: Package All Packages
        run: tar -czf openwrt-packages.tar.gz -C bin packages

      - name: Package Toolchain
        run: tar -czf openwrt-toolchain.tar.gz -C bin toolchain

      - name: Package SDK
        run: tar -czf openwrt-sdk.tar.gz -C bin sdk

      - name: Upload Firmware Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware-bpi-rv2
          path: bin/targets/siflower/sf21/*-sysupgrade.bin

      - name: Upload Packages Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-packages
          path: openwrt-packages.tar.gz

      - name: Upload Toolchain Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-toolchain
          path: openwrt-toolchain.tar.gz

      - name: Upload SDK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-sdk
          path: openwrt-sdk.tar.gz
